---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: vmartinvega/concourse-tools-tim
    tag: "latest"

inputs:
  - name: tools

run:
  path: tools/tasks/utils/clean-environment/task.sh
