---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: python
    tag: "2.7.15"

inputs:
  - name: repo

outputs:
  - name: keyvalout

run:
  path: tools/tasks/extract-pom-info/task.sh
