---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: vmartinvega/concourse-tools-tim
    tag: "latest"

inputs:
  - name: tools
  - name: repo
  - name: keyval

outputs:
  - name: out
  - name: keyvalout

run:
  path: tools/tasks/deploy/settingup-environment/task.sh
