---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: vmartinvega/concourse-tools-tim
    tag: "latest"

inputs:
  - name: tools
  - name: repoput1
  - name: out-release-step1
  - name: keyval

outputs:
  - name: keyvalout
  - name: out

run:
  path: tools/tasks/logical/create-release-step2/task.sh
