---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: vmartinvega/concourse-tools-tim
    tag: "latest"

inputs:
  - name: tools
  - name: repo
  - name: keyval
  - name: files

outputs:
  - name: filesout
  - name: out
  - name: keyvalout

run:
  path: tools/tasks/logical/create-release-step1/task.sh
