---
resources:
- name: repo
  type: git
  source:
    uri: ((app-url))
    branch: ((app-branch))
    username: ((github-username))
    password: ((github-password))
    skip_ssl_verification: true

- name: tools
  type: git
  source:
    uri: ((tools-scripts-url))
    branch: ((tools-branch))
    username: ((github-username))
    password: ((github-password))
    skip_ssl_verification: true

- name: keyval
  type: keyval

resource_types:
  - name: keyval
    type: docker-image
    source:
      repository: swce/keyval-resource

jobs:
- name: package
  public: true
  plan:
  - aggregate:
    - get: tools
    - get: repo
      trigger: true
  - task: package
    privileged: true
    file: tools/tasks/package/task.yml
  - put: keyval
    params:
      file: keyvalout/keyval.properties