---
resources:

- name: repo
  type: git
  source:
    uri: ((app-url))
    branch: ((app-branch))
    username: ((github-username))
    password: ((github-password))
    skip_ssl_verification: true

- name: tools
  type: git
  source:
    uri: ((tools-scripts-url))
    branch: ((tools-branch))
    username: ((github-tools-username))
    password: ((github-tools-password))
    skip_ssl_verification: true

- name: keyval
  type: keyval

resource_types:
  - name: keyval
    type: docker-image
    source:
      repository: swce/keyval-resource

jobs:

- name: archive-artifact
  public: true
  plan:
  - aggregate:
    - get: tools
    - get: repo
      trigger: true
  - task: archive-artifact
    privileged: true
    file: tools/tasks/archive-artifact/task.yml
    params:
      BUILD_OPTIONS: ((build-options))
      MAVEN_SETTINGS: ((maven-settings))
      TRUSTSTORE: ((truststore))
      BRANCHNAME: ((app-branch))
      USERNAME: ((github-username))
      PASSWORD: ((github-password))
      SONAR_BRANCH: ((sonar-branch))
  - put: keyval
    params:
      file: keyvalout/keyval.properties

  - put: repo
    params:
      repository: repo-modified
