---
resources:
- name: repo
  type: git
  source:
    uri: ((app-url))
    branch: ((app-branch))
    username: ((github-username))
    password: ((github-password))
    skip_ssl_verification: true

- name: tools
  type: git
  source:
    uri: ((tools-scripts-url))
    branch: ((tools-branch))
    username: ((github-tools-username))
    password: ((github-tools-password))
    skip_ssl_verification: true

- name: keyval
  type: keyval

resource_types:
  - name: keyval
    type: docker-image
    source:
      repository: swce/keyval-resource

jobs:
- name: build
  public: true
  plan:
  - aggregate:
    - get: tools
    - get: repo
      trigger: true
  - task: build
    privileged: true
    file: tools/tasks/build/task.yml
    params:
      BUILD_OPTIONS: ((build-options))
      TRUSTSTORE_FILE: ((truststore))
  - put: keyval
    params:
      file: keyvalout/keyval.properties

- name: unit-test
  public: true
  plan:
  - aggregate:
    - get: tools
    - get: repo
    - get: keyval
      passed:
      - build
      trigger: true
  - task: unit-test
    privileged: true
    file: tools/tasks/unit-test/task.yml
    params:
      BUILD_OPTIONS: ((build-options))
      TRUSTSTORE: ((truststore))
  - put: keyval
    params:
      file: keyvalout/keyval.properties

- name: sonarqube
  public: true
  plan:
  - aggregate:
    - get: tools
    - get: repo
    - get: keyval
      passed:
      - unit-test
      trigger: true
  - task: sonarqube
    privileged: true
    file: tools/tasks/sonarqube/task.yml
    params:
      BUILD_OPTIONS: ((build-options))
      TRUSTSTORE: ((truststore))
      SONAR_BRANCH: ((sonar-branch))
  - put: keyval
    params:
      file: keyvalout/keyval.properties

- name: archive-artifact
  public: true
  plan:
  - aggregate:
    - get: tools
    - get: repo
    - get: keyval
      passed:
      - sonarqube
      trigger: true
  - task: archive-artifact
    privileged: true
    file: tools/tasks/archive-artifact/task.yml
    params:
      BUILD_OPTIONS: ((build-options))
      TRUSTSTORE: ((truststore))
      SONAR_BRANCH: ((sonar-branch))
  - put: keyval
    params:
      file: keyvalout/keyval.properties
  - put: repo
    params:
      repository: repo-modified
