---
resources:
- name: repo
  type: git
  source:
    uri: ((app-url))
    branch: ((app-branch))
    username: ((github-username))
    password: ((github-password))
    skip_ssl_verification: true

- name: tools
  type: git
  source:
    uri: ((tools-scripts-url))
    branch: ((tools-branch))
    username: ((github-tools-username))
    password: ((github-tools-password))
    skip_ssl_verification: true

- name: keyval
  type: keyval

resource_types:
  - name: keyval
    type: docker-image
    source:
      repository: swce/keyval-resource

jobs:
- name: check-new-logical-release
  public: true
  plan:
  - aggregate:
    - get: tools
    - get: repo
      trigger: true
  - task: check-new-logical-release
    privileged: true
    file: tools/tasks/deploy/check-release/task.yml
    params:
      <<: *common-git-params
  - put: keyval
    params:
      file: keyvalout/keyval.properties

- name: setting-up-environment
  public: true
  plan:
  - aggregate:
    - get: tools
    - get: repo
    - get: keyval
      passed:
      - check-new-logical-release
      trigger: true
  - task: setting-up-environment
    privileged: true
    file: tools/tasks/deploy/settingup-environment/task.yml
    params:
      <<: *common-pcf-params
      NEXUS_USERNAME_FOR_SCDF: ((nexus-username-for-scdf))
      NEXUS_PASSWORD_FOR_SCDF: ((nexus-password-for-scdf))
      NEXUS_URL_FOR_SCDF: ((nexus-url-for-scdf))
      SCDF_SERVICE_NAME: ((scdf-service-name))
      SCDF_SERVICE_PLAN: ((scdf-service-plan))
      SCDF_ORG_FOR_SKIPPER_AND_DATAFLOW: ((scdf-org-for-skipper-and-dataflow))
      DEPLOY_SCDF_SERVICE_INSTANCE: ((deploy-scdf-service-instance))
      SCDF_SERVER_URL: ((scdf-server-url))
      DEPLOY_RABBITMQ_SERVICE_INSTANCE: ((deploy-rabbitmq-service-instance))
      RABBITMQ_SERVICE_NAME: ((rabbitmq-service-name))
      RABBITMQ_SERVICE_PLAN: ((rabbitmq-service-plan))
      DEPLOY_NFS_SERVICE_INSTANCE: ((deploy-nfs-service-instance))
      NFS_SERVICE_NAME: ((nfs-service-name))
      NFS_SERVICE_PLAN: ((nfs-service-plan))
      NFS_SHARE: ((nfs-share))
      NFS_USERNAME: ((nfs-username))
      NFS_PASSWORD: ((nfs-password))
  - put: keyval
    params:
      file: keyvalout/keyval.properties

- name: streams-deploy
  public: true
  plan:
  - aggregate:
    - get: tools
    - get: repo
    - get: keyval
      passed:
      - setting-up-environment
      trigger: true
  - task: streams-deploy
    privileged: true
    file: tools/tasks/deploy/do-nothing/task.yml
    params:
      <<: *common-pcf-params
  - put: keyval
    params:
      file: keyvalout/keyval.properties

- name: soapui-tests
  public: true
  plan:
  - aggregate:
    - get: tools
    - get: repo
    - get: keyval
      passed:
      - streams-deploy
      trigger: true
  - task: soapui-tests
    privileged: true
    file: tools/tasks/deploy/do-nothing/task.yml
    params:
      <<: *common-pcf-params
  - put: keyval
    params:
      file: keyvalout/keyval.properties

- name: undeploy-environment
  public: true
  plan:
  - aggregate:
    - get: tools
    - get: repo
    - get: keyval
      passed:
      - soapui-tests
      trigger: true
  - task: undeploy-environment
    privileged: true
    file: tools/tasks/deploy/do-nothing/task.yml
    params:
      <<: *common-pcf-params
      DEPLOY_SCDF_SERVICE_INSTANCE: ((deploy-scdf-service-instance))
      DEPLOY_NFS_SERVICE_INSTANCE: ((deploy-nfs-service-instance))
      DEPLOY_RABBITMQ_SERVICE_INSTANCE: ((deploy-rabbitmq-service-instance))
  - put: keyval
    params:
      file: keyvalout/keyval.properties

- name: prepare-release
  public: true
  plan:
  - aggregate:
    - get: tools
    - get: repo
    - get: keyval
      passed:
      - soapui-tests
      trigger: true
  - task: prepare-release
    privileged: true
    file: tools/tasks/deploy/prepare-release/task.yml
    params:
      <<: *common-git-params
  - put: keyval
    params:
      file: keyvalout/keyval.properties
  - put: repo
    params:
      repository: out

- name: create-release
  public: true
  plan:
  - aggregate:
    - get: tools
    - get: repo
    - get: keyval
      passed:
      - prepare-release
      trigger: true
  - task: create-release
    privileged: true
    file: tools/tasks/deploy/create-release/task.yml
    params:
      <<: *common-git-params
  - put: keyval
    params:
      file: keyvalout/keyval.properties

common-git-params: &common-git-params
  BUILD_OPTIONS: ((build-options))
  GIT_EMAIL: ((git-email))
  GIT_NAME: ((git-name))
  CURRENT_BRANCH: ((app-branch))
  TRUSTSTORE: ((truststore))
  GITHUB_PRIVATE_KEY: ((github-private-key))
  M2_SETTINGS_REPO_ID: ((m2-settings-repo-id))
  M2_SETTINGS_REPO_PASSWORD: ((m2-settings-repo-password))
  M2_SETTINGS_REPO_USERNAME: ((m2-settings-repo-username))
  M2_SETTINGS_REPO_MIRROR_URL: ((repo-with-binaries))
  M2_SETTINGS_REPO_SITE_URL: ((repo-with-site))
  M2_SETTINGS_REPO_RELEASE_URL: ((repo-with-binaries-for-upload))
  M2_SETTINGS_REPO_SNAPSHOTS_URL: ((repo-with-binaries-snapshots))
  M2_SETTINGS_REPO_GIT_SERVER_URL: ((gitlab-server-url))
  M2_SETTINGS_REPO_SONAR_URL: ((sonar-host-url))
  M2_SETTINGS_REPO_SONAR_TOKEN: ((sonar-login-key))

common-pcf-params: &common-pcf-params
  PWS_USER: ((pws-user))
  PWS_PWD: ((pws-pwd))
  PWS_ORG: ((pws-org))
  PWS_SPACE: ((pws-space))
  PWS_API: ((pws-api))
  ENVIRONMENT_DEPLOYING: ((environment-deploying))
