---
resources:
- name: repo
  type: git
  source:
    uri: ((app-url))
    branch: ((app-branch))
    username: ((github-username))
    password: ((github-password))
    skip_ssl_verification: true

- name: tools
  type: git
  source:
    uri: ((tools-scripts-url))
    branch: ((tools-branch))
    username: ((github-tools-username))
    password: ((github-tools-password))
    skip_ssl_verification: true

- name: keyval
  type: keyval

resource_types:
  - name: keyval
    type: docker-image
    source:
      repository: swce/keyval-resource

jobs:
- name: build
  public: true
  plan:
  - aggregate:
    - get: tools
    - get: repo
      trigger: true
  - task: build
    privileged: true
    file: tools/tasks/build/task.yml
    params:
      <<: *common-params
  - put: keyval
    params:
      file: keyvalout/keyval.properties

- name: unit-test
  public: true
  plan:
  - aggregate:
    - get: tools
    - get: repo
    - get: keyval
      passed:
      - build
      trigger: true
  - task: unit-test
    privileged: true
    file: tools/tasks/unit-test/task.yml
    params:
      <<: *common-params
  - put: keyval
    params:
      file: keyvalout/keyval.properties

- name: sonarqube
  public: true
  plan:
  - aggregate:
    - get: tools
    - get: repo
    - get: keyval
      passed:
      - unit-test
      trigger: true
  - task: sonarqube
    privileged: true
    file: tools/tasks/sonarqube/task.yml
    params:
      <<: *common-params
      SONAR_BRANCH: ((sonar-branch))
  - put: keyval
    params:
      file: keyvalout/keyval.properties

- name: archive-artifact
  public: true
  plan:
  - aggregate:
    - get: tools
    - get: repo
    - get: keyval
      passed:
      - sonarqube
      trigger: true
  - task: archive-artifact
    privileged: true
    file: tools/tasks/archive-artifact/task.yml
    params:
      <<: *common-params
      SONAR_BRANCH: ((sonar-branch))
  - put: keyval
    params:
      file: keyvalout/keyval.properties

common-params: &common-params
  BUILD_OPTIONS: ((build-options))
  GIT_EMAIL: ((git-email))
  GIT_NAME: ((git-name))
  CURRENT_BRANCH: ((app-branch))
  TRUSTSTORE: ((truststore))
  GITHUB_PRIVATE_KEY: ((github-private-key))
  M2_SETTINGS_REPO_ID: ((m2-settings-repo-id))
  M2_SETTINGS_REPO_PASSWORD: ((m2-settings-repo-password))
  M2_SETTINGS_REPO_USERNAME: ((m2-settings-repo-username))
  M2_SETTINGS_REPO_MIRROR_URL: ((repo-with-binaries))
  M2_SETTINGS_REPO_SITE_URL: ((repo-with-site))
  M2_SETTINGS_REPO_RELEASE_URL: ((repo-with-binaries-for-upload))
  M2_SETTINGS_REPO_SNAPSHOTS_URL: ((repo-with-binaries-snapshots))
  M2_SETTINGS_REPO_GIT_SERVER_URL: ((gitlab-server-url))
  M2_SETTINGS_REPO_SONAR_URL: ((sonar-host-url))
  M2_SETTINGS_REPO_SONAR_TOKEN: ((sonar-login-key))
