---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: vmartinvega/concourse-tools-tim
    tag: "latest"

inputs:
  - name: tools
  - name: out-preprare-release
  - name: keyval

outputs:
  - name: out-release-step1
  - name: keyvalout

run:
  path: tools/tasks/deploy/create-release-step1/task.sh
