---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: vmartinvega/concourse-tools-tim
    tag: "latest"

inputs:
  - name: tools
  - name: repo

outputs:
  - name: out
  - name: keyvalout

run:
  path: tools/tasks/physical/unit-test/task.sh
