---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: pivotalservices/docker-concourse-cf-tools
    tag: "latest"

inputs:
  - name: tools
  - name: repo

outputs:
  - name: out
  - name: keyvalout

run:
  path: tools/tasks/scdf-server-deploy/task.sh
