version: '3'

services:
  concourse-db:
    image: postgres
    environment:
    - POSTGRES_DB=concourse
    - POSTGRES_PASSWORD=concourse_pass
    - POSTGRES_USER=concourse_user
    - PGDATA=/database
    extra_hosts:
      - "gitlab-sdp.telecomitalia.local:10.0.69.84"
      - "nexus-sdp.telecomitalia.local:10.0.69.85"
      - "sonar-sdp.telecomitalia.local:10.0.69.86"

  concourse-web:
    image: concourse/concourse
    command: web
    links: [concourse-db]
    depends_on: [concourse-db]
    ports: ["8080:8080"]
    volumes: ["./keys/web:/concourse-keys"]
    environment:
    - CONCOURSE_POSTGRES_HOST=concourse-db
    - CONCOURSE_POSTGRES_USER=concourse_user
    - CONCOURSE_POSTGRES_PASSWORD=concourse_pass
    - CONCOURSE_POSTGRES_DATABASE=concourse
    - CONCOURSE_EXTERNAL_URL
    - CONCOURSE_BASIC_AUTH_USERNAME
    - CONCOURSE_BASIC_AUTH_PASSWORD
    - CONCOURSE_NO_REALLY_I_DONT_WANT_ANY_AUTH=true
    extra_hosts:
      - "gitlab-sdp.telecomitalia.local:10.0.69.84"
      - "nexus-sdp.telecomitalia.local:10.0.69.85"
      - "sonar-sdp.telecomitalia.local:10.0.69.86" 

  concourse-worker:
    image: concourse/concourse
    command: worker
    privileged: true
    links: [concourse-web]
    depends_on: [concourse-web]
    volumes: ["./keys/worker:/concourse-keys"]
    environment:
    - CONCOURSE_TSA_HOST=concourse-web:2222
    - CONCOURSE_GARDEN_NETWORK
    extra_hosts:
      - "gitlab-sdp.telecomitalia.local:10.0.69.84"
      - "nexus-sdp.telecomitalia.local:10.0.69.85"
      - "sonar-sdp.telecomitalia.local:10.0.69.86"
