---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: pivotalservices/docker-concourse-cf-tools
    tag: "latest"

inputs:
  - name: tools
  - name: repo
  - name: keyval

outputs:
  - name: out
  - name: keyvalout

run:
  path: tools/tasks/stream-deploy/task.sh
