---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: java
    tag: "8"

inputs:
  - name: tools
  - name: repo

outputs:
  - name: out
  - name: keyvalout

run:
  path: tools/tasks/package/task.sh